<?php
defined('ABSPATH') || exit;

final class WM_REST {
    public static function boot(): void { add_action('rest_api_init', [self::class, 'routes']); add_action('woocommerce_order_status_processing',[self::class,'auto_register']); }
    public static function routes(): void {
        register_rest_route('woo-manager/v1', '/pair', ['methods'=>'POST','callback'=>[self::class,'pair'],'permission_callback'=>'__return_true']);
        register_rest_route('woo-manager/v1', '/health', ['methods'=>'GET','callback'=>[self::class,'health'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/orders', ['methods'=>'GET','callback'=>[self::class,'orders'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/orders/(?P<order_id>\d+)', [
            ['methods'=>'GET','callback'=>[self::class,'order_detail'],'permission_callback'=>[self::class,'can_manage']],
            ['methods'=>'PATCH','callback'=>[self::class,'update_order'],'permission_callback'=>[self::class,'can_manage']],
        ]);
        register_rest_route('woo-manager/v1', '/orders/(?P<order_id>\d+)/notes', ['methods'=>'POST','callback'=>[self::class,'add_note'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/orders/(?P<order_id>\d+)/refunds', ['methods'=>'POST','callback'=>[self::class,'create_refund'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/products', ['methods'=>'GET','callback'=>[self::class,'products'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/products/(?P<product_id>\d+)', [
            ['methods'=>'GET','callback'=>[self::class,'product_detail'],'permission_callback'=>[self::class,'can_manage']],
            ['methods'=>'PATCH','callback'=>[self::class,'update_product'],'permission_callback'=>[self::class,'can_manage']],
        ]);
        register_rest_route('woo-manager/v1', '/products/(?P<product_id>\d+)/variations/(?P<variation_id>\d+)', ['methods'=>'PATCH','callback'=>[self::class,'update_variation'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/customers', ['methods'=>'GET','callback'=>[self::class,'customers'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/customers/(?P<customer_id>\d+)', [
            ['methods'=>'GET','callback'=>[self::class,'customer_detail'],'permission_callback'=>[self::class,'can_manage']],
            ['methods'=>'PATCH','callback'=>[self::class,'update_customer'],'permission_callback'=>[self::class,'can_manage']],
        ]);
        register_rest_route('woo-manager/v1', '/reports/summary', ['methods'=>'GET','callback'=>[self::class,'report_summary'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/coupons', [
            ['methods'=>'GET','callback'=>[self::class,'coupons'],'permission_callback'=>[self::class,'can_manage']],
            ['methods'=>'POST','callback'=>[self::class,'create_coupon'],'permission_callback'=>[self::class,'can_manage']],
        ]);
        register_rest_route('woo-manager/v1', '/coupons/(?P<coupon_id>\d+)', ['methods'=>'PATCH','callback'=>[self::class,'update_coupon'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/reviews', ['methods'=>'GET','callback'=>[self::class,'reviews'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/reviews/(?P<review_id>\d+)', ['methods'=>'PATCH','callback'=>[self::class,'update_review'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/notifications', ['methods'=>'GET','callback'=>[self::class,'notifications'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/system', ['methods'=>'GET','callback'=>[self::class,'system'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/devices', ['methods'=>'GET','callback'=>[self::class,'devices'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/devices/(?P<device_id>\d+)/revoke', ['methods'=>'POST','callback'=>[self::class,'revoke_device'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/tests/tapin', ['methods'=>'POST','callback'=>[self::class,'test_tapin'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/tests/sms', ['methods'=>'POST','callback'=>[self::class,'test_sms'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/logs', ['methods'=>'GET','callback'=>[self::class,'logs'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/media', [
            ['methods'=>'GET','callback'=>[self::class,'media'],'permission_callback'=>[self::class,'can_manage']],
            ['methods'=>'POST','callback'=>[self::class,'upload_media'],'permission_callback'=>[self::class,'can_manage']],
        ]);
        register_rest_route('woo-manager/v1', '/content', ['methods'=>'GET','callback'=>[self::class,'content'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/content/(?P<content_id>\d+)', ['methods'=>'PATCH','callback'=>[self::class,'update_content'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/tapin/register/(?P<order_id>\d+)', ['methods'=>'POST','callback'=>[self::class,'tapin_register'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/tapin/label', ['methods'=>'POST','callback'=>[self::class,'tapin_label'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/tapin/invoice', ['methods'=>'POST','callback'=>[self::class,'tapin_invoice'],'permission_callback'=>[self::class,'can_manage']]);
        register_rest_route('woo-manager/v1', '/tapin/pdf', ['methods'=>'POST','callback'=>[self::class,'tapin_pdf'],'permission_callback'=>[self::class,'can_manage']]);
    }
    public static function can_manage(WP_REST_Request $request): bool { return current_user_can('manage_woocommerce') || WM_Devices::authenticate($request); }
    public static function pair(WP_REST_Request $request) {
        $p=(array)$request->get_json_params();
        if (!preg_match('/^\d{6}$/',(string)($p['code']??'')) || empty($p['device_id'])) return new WP_Error('invalid_pair_request','کد شش‌رقمی و شناسه دستگاه الزامی است.',['status'=>422]);
        return WM_Devices::exchange((string)$p['code'],sanitize_text_field($p['device_id']),sanitize_text_field($p['device_name']??'Mobile'));
    }
    public static function health(): WP_REST_Response {
        return rest_ensure_response(['ok'=>true,'version'=>WOO_MANAGER_VERSION,'woocommerce'=>class_exists('WooCommerce'),'tapin'=>WM_Tapin::health(),'sms_provider'=>WM_Settings::get('sms_provider','melipayamak')]);
    }
    public static function orders(WP_REST_Request $request) {
        if (!function_exists('wc_get_orders')) return new WP_Error('woocommerce_missing','ووکامرس فعال نیست.',['status'=>503]);
        $orders = wc_get_orders(['limit'=>min(50,max(1,(int)$request->get_param('limit'))),'orderby'=>'date','order'=>'DESC']);
        return rest_ensure_response(array_map(static function($order){
            $created = $order->get_date_created();
            return ['id'=>$order->get_id(),'status'=>$order->get_status(),'total'=>$order->get_total(),'currency'=>$order->get_currency(),'customer'=>$order->get_formatted_billing_full_name(),'date'=>$created ? $created->date(DATE_ATOM) : null,'tapin_order_id'=>$order->get_meta('_tapin_order_id')?:null,'tapin_uuid'=>$order->get_meta('_tapin_uuid')?:null,'tracking_number'=>$order->get_meta('_tracking_number')?:null];
        }, $orders));
    }
    private static function get_order(WP_REST_Request $request) {
        if (!function_exists('wc_get_order')) return new WP_Error('woocommerce_missing','ووکامرس فعال نیست.',['status'=>503]);
        $order=wc_get_order(absint($request['order_id']));
        return $order ?: new WP_Error('order_not_found','سفارش پیدا نشد.',['status'=>404]);
    }
    private static function address(WC_Order $order,string $type): array {
        $shipping=$type==='shipping';
        $get=static function(string $field) use($order,$shipping){$method='get_'.($shipping?'shipping_':'billing_').$field;return method_exists($order,$method)?$order->{$method}():'';};
        return ['first_name'=>$get('first_name'),'last_name'=>$get('last_name'),'company'=>$get('company'),'address_1'=>$get('address_1'),'address_2'=>$get('address_2'),'city'=>$get('city'),'state'=>$get('state'),'postcode'=>$get('postcode'),'country'=>$get('country'),'phone'=>$shipping && method_exists($order,'get_shipping_phone')?$order->get_shipping_phone():$order->get_billing_phone(),'email'=>$order->get_billing_email()];
    }
    private static function serialize_order(WC_Order $order): array {
        $items=[];
        foreach($order->get_items() as $item){$product=$item->get_product();$items[]=['id'=>$item->get_id(),'product_id'=>$item->get_product_id(),'variation_id'=>$item->get_variation_id(),'name'=>$item->get_name(),'quantity'=>(int)$item->get_quantity(),'subtotal'=>$item->get_subtotal(),'total'=>$item->get_total(),'sku'=>$product?$product->get_sku():'','image'=>$product&&$product->get_image_id()?wp_get_attachment_image_url($product->get_image_id(),'thumbnail'):null,'meta'=>array_values(array_map(static function($meta){return ['key'=>$meta->display_key,'value'=>wp_strip_all_tags((string)$meta->display_value)];},$item->get_formatted_meta_data('')) )];}
        $notes=wc_get_order_notes(['order_id'=>$order->get_id(),'limit'=>100,'orderby'=>'date_created','order'=>'DESC']);
        $history=array_map(static function($note){return ['id'=>$note->id,'content'=>wp_strip_all_tags($note->content),'customer_note'=>(bool)$note->customer_note,'date'=>$note->date_created?$note->date_created->date(DATE_ATOM):null,'author'=>$note->added_by];},$notes);
        $refunds=array_map(static function($refund){$created=$refund->get_date_created();return ['id'=>$refund->get_id(),'amount'=>$refund->get_amount(),'reason'=>$refund->get_reason(),'date'=>$created?$created->date(DATE_ATOM):null];},$order->get_refunds());
        $created=$order->get_date_created();$updated=$order->get_date_modified();
        return ['id'=>$order->get_id(),'number'=>$order->get_order_number(),'status'=>$order->get_status(),'status_options'=>array_map(static fn($label,$key)=>['value'=>str_replace('wc-','',$key),'label'=>$label],wc_get_order_statuses(),array_keys(wc_get_order_statuses())),'currency'=>$order->get_currency(),'total'=>$order->get_total(),'subtotal'=>$order->get_subtotal(),'discount_total'=>$order->get_discount_total(),'shipping_total'=>$order->get_shipping_total(),'tax_total'=>$order->get_total_tax(),'total_refunded'=>$order->get_total_refunded(),'refundable_amount'=>$order->get_remaining_refund_amount(),'payment_method'=>$order->get_payment_method_title(),'transaction_id'=>$order->get_transaction_id(),'customer_note'=>$order->get_customer_note(),'created_at'=>$created?$created->date(DATE_ATOM):null,'updated_at'=>$updated?$updated->date(DATE_ATOM):null,'billing'=>self::address($order,'billing'),'shipping'=>self::address($order,'shipping'),'shipping_method'=>$order->get_shipping_method(),'items'=>$items,'refunds'=>$refunds,'history'=>$history,'shipment'=>['tapin_order_id'=>$order->get_meta('_tapin_order_id')?:null,'tapin_uuid'=>$order->get_meta('_tapin_uuid')?:null,'tracking_number'=>$order->get_meta('_tracking_number')?:null,'province_code'=>$order->get_meta('_tapin_province_code')?:null,'city_code'=>$order->get_meta('_tapin_city_code')?:null,'tapin'=>$order->get_meta('_woo_manager_tapin')?:null]];
    }
    public static function order_detail(WP_REST_Request $request){$order=self::get_order($request);return is_wp_error($order)?$order:rest_ensure_response(self::serialize_order($order));}
    public static function update_order(WP_REST_Request $request){
        $order=self::get_order($request);if(is_wp_error($order))return $order;$p=(array)$request->get_json_params();$status=sanitize_key((string)($p['status']??''));$allowed=array_map(static fn($key)=>str_replace('wc-','',$key),array_keys(wc_get_order_statuses()));if(!$status||!in_array($status,$allowed,true))return new WP_Error('invalid_status','وضعیت سفارش معتبر نیست.',['status'=>422]);
        try{$order->update_status($status,'وضعیت از اپ Woo Manager تغییر کرد.',true);return rest_ensure_response(self::serialize_order($order));}catch(Throwable $e){return new WP_Error('status_update_failed',$e->getMessage(),['status'=>500]);}
    }
    public static function add_note(WP_REST_Request $request){
        $order=self::get_order($request);if(is_wp_error($order))return $order;$p=(array)$request->get_json_params();$content=trim(sanitize_textarea_field((string)($p['content']??'')));if($content==='')return new WP_Error('empty_note','متن یادداشت الزامی است.',['status'=>422]);$customer_note=rest_sanitize_boolean($p['customer_note']??false);$id=$order->add_order_note($content,$customer_note,true);return new WP_REST_Response(['id'=>$id,'order'=>self::serialize_order($order)],201);
    }
    public static function create_refund(WP_REST_Request $request){
        $order=self::get_order($request);if(is_wp_error($order))return $order;$p=(array)$request->get_json_params();if(($p['confirm']??false)!==true)return new WP_Error('refund_confirmation_required','برای بازپرداخت، تأیید صریح الزامی است.',['status'=>409]);$amount=(float)wc_format_decimal($p['amount']??0);$remaining=(float)$order->get_remaining_refund_amount();if($amount<=0||$amount>$remaining)return new WP_Error('invalid_refund_amount','مبلغ بازپرداخت باید بیشتر از صفر و حداکثر مبلغ قابل بازپرداخت باشد.',['status'=>422]);
        $refund=wc_create_refund(['order_id'=>$order->get_id(),'amount'=>$amount,'reason'=>sanitize_text_field((string)($p['reason']??'')),'refund_payment'=>rest_sanitize_boolean($p['refund_payment']??false),'restock_items'=>rest_sanitize_boolean($p['restock_items']??false)]);if(is_wp_error($refund))return $refund;$order->add_order_note(sprintf('بازپرداخت مبلغ %s از اپ Woo Manager ثبت شد.',wc_price($amount,['currency'=>$order->get_currency()])));return new WP_REST_Response(['refund_id'=>$refund->get_id(),'order'=>self::serialize_order($order)],201);
    }
    private static function product_summary(WC_Product $product): array {
        $image_id=$product->get_image_id();
        return ['id'=>$product->get_id(),'name'=>$product->get_name(),'type'=>$product->get_type(),'status'=>$product->get_status(),'sku'=>$product->get_sku(),'price'=>$product->get_price(),'regular_price'=>$product->get_regular_price(),'sale_price'=>$product->get_sale_price(),'stock_status'=>$product->get_stock_status(),'stock_quantity'=>$product->get_stock_quantity(),'manage_stock'=>$product->get_manage_stock(),'featured'=>$product->get_featured(),'image'=>$image_id?wp_get_attachment_image_url($image_id,'woocommerce_thumbnail'):null];
    }
    private static function serialize_product(WC_Product $product): array {
        $data=self::product_summary($product);$images=[];
        foreach(array_filter(array_merge([$product->get_image_id()],$product->get_gallery_image_ids())) as $image_id){$images[]=['id'=>(int)$image_id,'src'=>wp_get_attachment_image_url($image_id,'large'),'thumbnail'=>wp_get_attachment_image_url($image_id,'woocommerce_thumbnail')];}
        $categories=array_map(static fn($term)=>['id'=>$term->term_id,'name'=>$term->name],wp_get_post_terms($product->get_id(),'product_cat'));
        $attributes=[];foreach($product->get_attributes() as $attribute){$attributes[]=['name'=>wc_attribute_label($attribute->get_name()),'options'=>$attribute->is_taxonomy()?wc_get_product_terms($product->get_id(),$attribute->get_name(),['fields'=>'names']):$attribute->get_options(),'variation'=>$attribute->get_variation(),'visible'=>$attribute->get_visible()];}
        $variations=[];if($product->is_type('variable')){foreach($product->get_children() as $variation_id){$variation=wc_get_product($variation_id);if($variation)$variations[]=array_merge(self::product_summary($variation),['attributes'=>$variation->get_attributes()]);}}
        return array_merge($data,['description'=>$product->get_description(),'short_description'=>$product->get_short_description(),'weight'=>$product->get_weight(),'dimensions'=>['length'=>$product->get_length(),'width'=>$product->get_width(),'height'=>$product->get_height()],'categories'=>$categories,'attributes'=>$attributes,'images'=>$images,'variations'=>$variations,'permalink'=>$product->get_permalink(),'date_modified'=>$product->get_date_modified()?$product->get_date_modified()->date(DATE_ATOM):null]);
    }
    public static function products(WP_REST_Request $request){
        if(!function_exists('wc_get_products'))return new WP_Error('woocommerce_missing','ووکامرس فعال نیست.',['status'=>503]);$limit=min(50,max(1,(int)($request->get_param('limit')?:30)));$page=max(1,(int)($request->get_param('page')?:1));$args=['limit'=>$limit,'page'=>$page,'paginate'=>true,'orderby'=>'date','order'=>'DESC'];$search=trim(sanitize_text_field((string)$request->get_param('search')));if($search!=='')$args['s']=$search;$status=sanitize_key((string)$request->get_param('status'));if($status!=='')$args['status']=$status;$result=wc_get_products($args);return rest_ensure_response(['items'=>array_map([self::class,'product_summary'],$result->products),'total'=>(int)$result->total,'pages'=>(int)$result->max_num_pages,'page'=>$page]);
    }
    private static function get_product(WP_REST_Request $request){$product=wc_get_product(absint($request['product_id']));return $product?:new WP_Error('product_not_found','محصول پیدا نشد.',['status'=>404]);}
    public static function product_detail(WP_REST_Request $request){$product=self::get_product($request);return is_wp_error($product)?$product:rest_ensure_response(self::serialize_product($product));}
    public static function update_product(WP_REST_Request $request){
        $product=self::get_product($request);if(is_wp_error($product))return $product;$p=(array)$request->get_json_params();
        if(array_key_exists('name',$p))$product->set_name(sanitize_text_field((string)$p['name']));if(array_key_exists('sku',$p)){$sku=wc_clean((string)$p['sku']);try{$product->set_sku($sku);}catch(Exception $e){return new WP_Error('invalid_sku',$e->getMessage(),['status'=>422]);}}
        foreach(['regular_price','sale_price'] as $field){if(array_key_exists($field,$p)){$value=$p[$field]===''?'':wc_format_decimal($p[$field]);$method='set_'.$field;$product->{$method}($value);}}
        if(array_key_exists('manage_stock',$p))$product->set_manage_stock(rest_sanitize_boolean($p['manage_stock']));if(array_key_exists('stock_quantity',$p)&&$product->get_manage_stock())$product->set_stock_quantity(max(0,(int)$p['stock_quantity']));
        if(array_key_exists('stock_status',$p)){if(!in_array($p['stock_status'],['instock','outofstock','onbackorder'],true))return new WP_Error('invalid_stock_status','وضعیت موجودی معتبر نیست.',['status'=>422]);$product->set_stock_status($p['stock_status']);}
        if(array_key_exists('status',$p)){if(!in_array($p['status'],['publish','draft','pending','private'],true))return new WP_Error('invalid_product_status','وضعیت انتشار معتبر نیست.',['status'=>422]);$product->set_status($p['status']);}
        if(array_key_exists('featured',$p))$product->set_featured(rest_sanitize_boolean($p['featured']));if(array_key_exists('description',$p))$product->set_description(wp_kses_post((string)$p['description']));if(array_key_exists('short_description',$p))$product->set_short_description(wp_kses_post((string)$p['short_description']));
        try{$product->save();return rest_ensure_response(self::serialize_product($product));}catch(Throwable $e){return new WP_Error('product_update_failed',$e->getMessage(),['status'=>500]);}
    }
    public static function update_variation(WP_REST_Request $request){
        $parent=self::get_product($request);if(is_wp_error($parent))return $parent;$variation=wc_get_product(absint($request['variation_id']));if(!$variation||!$variation->is_type('variation')||(int)$variation->get_parent_id()!==$parent->get_id())return new WP_Error('variation_not_found','متغیر محصول پیدا نشد.',['status'=>404]);$p=(array)$request->get_json_params();foreach(['regular_price','sale_price'] as $field){if(array_key_exists($field,$p)){$method='set_'.$field;$variation->{$method}($p[$field]===''?'':wc_format_decimal($p[$field]));}}if(array_key_exists('manage_stock',$p))$variation->set_manage_stock(rest_sanitize_boolean($p['manage_stock']));if(array_key_exists('stock_quantity',$p)&&$variation->get_manage_stock())$variation->set_stock_quantity(max(0,(int)$p['stock_quantity']));if(array_key_exists('stock_status',$p)){if(!in_array($p['stock_status'],['instock','outofstock','onbackorder'],true))return new WP_Error('invalid_stock_status','وضعیت موجودی معتبر نیست.',['status'=>422]);$variation->set_stock_status($p['stock_status']);}try{$variation->save();return rest_ensure_response(self::serialize_product($parent));}catch(Throwable $e){return new WP_Error('variation_update_failed',$e->getMessage(),['status'=>500]);}
    }
    private static function customer_summary(WC_Customer $customer): array {
        $avatar=get_avatar_url($customer->get_id(),['size'=>128]);
        return ['id'=>$customer->get_id(),'first_name'=>$customer->get_first_name(),'last_name'=>$customer->get_last_name(),'display_name'=>$customer->get_display_name(),'email'=>$customer->get_email(),'phone'=>$customer->get_billing_phone(),'avatar'=>$avatar?:null,'orders_count'=>$customer->get_order_count(),'total_spent'=>$customer->get_total_spent(),'date_created'=>$customer->get_date_created()?$customer->get_date_created()->date(DATE_ATOM):null];
    }
    private static function customer_address(WC_Customer $customer,string $type): array {$get=static function(string $field)use($customer,$type){$method='get_'.$type.'_'.$field;return method_exists($customer,$method)?$customer->{$method}():'';};return ['first_name'=>$get('first_name'),'last_name'=>$get('last_name'),'company'=>$get('company'),'address_1'=>$get('address_1'),'address_2'=>$get('address_2'),'city'=>$get('city'),'state'=>$get('state'),'postcode'=>$get('postcode'),'country'=>$get('country'),'phone'=>$type==='billing'?$get('phone'):'','email'=>$type==='billing'?$get('email'):''];}
    private static function serialize_customer(WC_Customer $customer): array {
        $orders=wc_get_orders(['customer_id'=>$customer->get_id(),'limit'=>50,'orderby'=>'date','order'=>'DESC']);$order_items=array_map(static function($order){$date=$order->get_date_created();return ['id'=>$order->get_id(),'number'=>$order->get_order_number(),'status'=>$order->get_status(),'total'=>$order->get_total(),'currency'=>$order->get_currency(),'date'=>$date?$date->date(DATE_ATOM):null];},$orders);
        return array_merge(self::customer_summary($customer),['username'=>$customer->get_username(),'role'=>$customer->get_role(),'billing'=>self::customer_address($customer,'billing'),'shipping'=>self::customer_address($customer,'shipping'),'orders'=>$order_items,'last_order'=>$order_items[0]??null]);
    }
    public static function customers(WP_REST_Request $request){
        if(!class_exists('WC_Customer'))return new WP_Error('woocommerce_missing','ووکامرس فعال نیست.',['status'=>503]);$limit=min(50,max(1,(int)($request->get_param('limit')?:30)));$page=max(1,(int)($request->get_param('page')?:1));$args=['number'=>$limit,'offset'=>($page-1)*$limit,'orderby'=>'registered','order'=>'DESC','role'=>'customer'];$search=trim(sanitize_text_field((string)$request->get_param('search')));if($search!==''){$args['search']='*'.$search.'*';$args['search_columns']=['user_login','user_email','display_name'];}$query=new WP_User_Query($args);$items=[];foreach($query->get_results() as $user)$items[]=self::customer_summary(new WC_Customer($user->ID));return rest_ensure_response(['items'=>$items,'total'=>(int)$query->get_total(),'pages'=>(int)ceil($query->get_total()/$limit),'page'=>$page]);
    }
    private static function get_customer(WP_REST_Request $request){$id=absint($request['customer_id']);if(!$id||!get_userdata($id))return new WP_Error('customer_not_found','مشتری پیدا نشد.',['status'=>404]);return new WC_Customer($id);}
    public static function customer_detail(WP_REST_Request $request){$customer=self::get_customer($request);return is_wp_error($customer)?$customer:rest_ensure_response(self::serialize_customer($customer));}
    public static function update_customer(WP_REST_Request $request){
        $customer=self::get_customer($request);if(is_wp_error($customer))return $customer;$p=(array)$request->get_json_params();foreach(['first_name','last_name'] as $field){if(array_key_exists($field,$p)){$method='set_'.$field;$customer->{$method}(sanitize_text_field((string)$p[$field]));}}if(array_key_exists('email',$p)){if(!is_email($p['email']))return new WP_Error('invalid_email','ایمیل معتبر نیست.',['status'=>422]);try{$customer->set_email(sanitize_email($p['email']));}catch(Exception $e){return new WP_Error('email_exists',$e->getMessage(),['status'=>422]);}}
        foreach(['billing','shipping'] as $type){if(!isset($p[$type])||!is_array($p[$type]))continue;foreach(['first_name','last_name','company','address_1','address_2','city','state','postcode','country'] as $field){if(array_key_exists($field,$p[$type])){$method='set_'.$type.'_'.$field;$customer->{$method}(sanitize_text_field((string)$p[$type][$field]));}}}if(isset($p['billing']['phone']))$customer->set_billing_phone(sanitize_text_field((string)$p['billing']['phone']));if(isset($p['billing']['email'])&&is_email($p['billing']['email']))$customer->set_billing_email(sanitize_email($p['billing']['email']));
        try{$customer->save();return rest_ensure_response(self::serialize_customer($customer));}catch(Throwable $e){return new WP_Error('customer_update_failed',$e->getMessage(),['status'=>500]);}
    }
    public static function report_summary(WP_REST_Request $request){
        if(!function_exists('wc_get_orders'))return new WP_Error('woocommerce_missing','ووکامرس فعال نیست.',['status'=>503]);$days=(int)$request->get_param('days');if(!in_array($days,[7,30,90],true))$days=30;$timezone=wp_timezone();$today=new DateTimeImmutable('today',$timezone);$start=$today->modify('-'.($days-1).' days');$orders=wc_get_orders(['limit'=>-1,'date_created'=>'>='.$start->format('Y-m-d H:i:s'),'orderby'=>'date','order'=>'ASC']);$paid_statuses=wc_get_is_paid_statuses();$status_counts=[];$daily=[];$products=[];$revenue=0.0;$paid_count=0;
        for($i=0;$i<$days;$i++){$date=$start->modify('+'.$i.' days')->format('Y-m-d');$daily[$date]=0.0;}
        foreach($orders as $order){$status=$order->get_status();$status_counts[$status]=($status_counts[$status]??0)+1;if(!in_array($status,$paid_statuses,true))continue;$paid_count++;$net=max(0,(float)$order->get_total()-(float)$order->get_total_refunded());$revenue+=$net;$created=$order->get_date_created();if($created){$key=$created->date('Y-m-d');if(array_key_exists($key,$daily))$daily[$key]+=$net;}foreach($order->get_items() as $item){$product_id=$item->get_product_id();if(!$product_id)continue;if(!isset($products[$product_id]))$products[$product_id]=['product_id'=>$product_id,'name'=>$item->get_name(),'quantity'=>0,'revenue'=>0.0];$products[$product_id]['quantity']+=(int)$item->get_quantity();$products[$product_id]['revenue']+=(float)$item->get_total();}}
        uasort($products,static fn($a,$b)=>$b['quantity']<=>$a['quantity']);$top=array_slice(array_values($products),0,10);$series=[];foreach($daily as $date=>$amount)$series[]=['date'=>$date,'revenue'=>wc_format_decimal($amount,2)];$statuses=[];foreach(wc_get_order_statuses() as $key=>$label){$value=str_replace('wc-','',$key);$statuses[]=['status'=>$value,'label'=>$label,'count'=>(int)($status_counts[$value]??0)];}
        return rest_ensure_response(['days'=>$days,'currency'=>get_woocommerce_currency(),'revenue'=>wc_format_decimal($revenue,2),'orders_count'=>count($orders),'paid_orders_count'=>$paid_count,'average_order_value'=>wc_format_decimal($paid_count?$revenue/$paid_count:0,2),'refunded'=>wc_format_decimal(array_sum(array_map(static fn($order)=>(float)$order->get_total_refunded(),$orders)),2),'daily'=>$series,'statuses'=>$statuses,'top_products'=>$top,'generated_at'=>current_time(DATE_ATOM)]);
    }
    private static function serialize_coupon(WC_Coupon $coupon): array {$expires=$coupon->get_date_expires();return ['id'=>$coupon->get_id(),'code'=>$coupon->get_code(),'description'=>$coupon->get_description(),'discount_type'=>$coupon->get_discount_type(),'amount'=>$coupon->get_amount(),'usage_count'=>$coupon->get_usage_count(),'usage_limit'=>$coupon->get_usage_limit(),'individual_use'=>$coupon->get_individual_use(),'free_shipping'=>$coupon->get_free_shipping(),'minimum_amount'=>$coupon->get_minimum_amount(),'maximum_amount'=>$coupon->get_maximum_amount(),'date_expires'=>$expires?$expires->date('Y-m-d'):null];}
    public static function coupons(WP_REST_Request $request){$limit=min(50,max(1,(int)($request->get_param('limit')?:30)));$page=max(1,(int)($request->get_param('page')?:1));$query=new WP_Query(['post_type'=>'shop_coupon','post_status'=>'publish','posts_per_page'=>$limit,'paged'=>$page,'s'=>sanitize_text_field((string)$request->get_param('search')),'orderby'=>'date','order'=>'DESC']);$items=[];foreach($query->posts as $post)$items[]=self::serialize_coupon(new WC_Coupon($post->ID));return rest_ensure_response(['items'=>$items,'total'=>(int)$query->found_posts,'pages'=>(int)$query->max_num_pages,'page'=>$page]);}
    private static function apply_coupon(WC_Coupon $coupon,array $p){if(array_key_exists('code',$p))$coupon->set_code(wc_format_coupon_code($p['code']));if(array_key_exists('description',$p))$coupon->set_description(sanitize_textarea_field((string)$p['description']));if(array_key_exists('discount_type',$p)){if(!in_array($p['discount_type'],['percent','fixed_cart','fixed_product'],true))return new WP_Error('invalid_discount_type','نوع تخفیف معتبر نیست.',['status'=>422]);$coupon->set_discount_type($p['discount_type']);}if(array_key_exists('amount',$p))$coupon->set_amount(max(0,(float)wc_format_decimal($p['amount'])));if(array_key_exists('usage_limit',$p))$coupon->set_usage_limit(max(0,(int)$p['usage_limit']));if(array_key_exists('individual_use',$p))$coupon->set_individual_use(rest_sanitize_boolean($p['individual_use']));if(array_key_exists('free_shipping',$p))$coupon->set_free_shipping(rest_sanitize_boolean($p['free_shipping']));if(array_key_exists('minimum_amount',$p))$coupon->set_minimum_amount(wc_format_decimal($p['minimum_amount']));if(array_key_exists('maximum_amount',$p))$coupon->set_maximum_amount(wc_format_decimal($p['maximum_amount']));if(array_key_exists('date_expires',$p))$coupon->set_date_expires($p['date_expires']?:null);return $coupon;}
    public static function create_coupon(WP_REST_Request $request){$p=(array)$request->get_json_params();if(trim((string)($p['code']??''))==='')return new WP_Error('coupon_code_required','کد تخفیف الزامی است.',['status'=>422]);$coupon=self::apply_coupon(new WC_Coupon(),$p);if(is_wp_error($coupon))return $coupon;try{$coupon->save();return new WP_REST_Response(self::serialize_coupon($coupon),201);}catch(Throwable $e){return new WP_Error('coupon_create_failed',$e->getMessage(),['status'=>422]);}}
    public static function update_coupon(WP_REST_Request $request){$coupon=new WC_Coupon(absint($request['coupon_id']));if(!$coupon->get_id())return new WP_Error('coupon_not_found','کد تخفیف پیدا نشد.',['status'=>404]);$coupon=self::apply_coupon($coupon,(array)$request->get_json_params());if(is_wp_error($coupon))return $coupon;try{$coupon->save();return rest_ensure_response(self::serialize_coupon($coupon));}catch(Throwable $e){return new WP_Error('coupon_update_failed',$e->getMessage(),['status'=>422]);}}
    private static function serialize_review(WP_Comment $comment): array {return ['id'=>(int)$comment->comment_ID,'product_id'=>(int)$comment->comment_post_ID,'product_name'=>get_the_title($comment->comment_post_ID),'author'=>$comment->comment_author,'email'=>$comment->comment_author_email,'content'=>$comment->comment_content,'rating'=>(int)get_comment_meta($comment->comment_ID,'rating',true),'status'=>wp_get_comment_status($comment),'date'=>get_comment_date(DATE_ATOM,$comment),'avatar'=>get_avatar_url($comment->comment_author_email,['size'=>96])];}
    public static function reviews(WP_REST_Request $request){$status=sanitize_key((string)($request->get_param('status')?:'all'));$args=['type'=>'review','number'=>50,'orderby'=>'comment_date_gmt','order'=>'DESC'];if(in_array($status,['approve','hold','spam','trash'],true))$args['status']=$status;$comments=get_comments($args);return rest_ensure_response(array_map([self::class,'serialize_review'],$comments));}
    public static function update_review(WP_REST_Request $request){$id=absint($request['review_id']);$comment=get_comment($id);if(!$comment||$comment->comment_type!=='review')return new WP_Error('review_not_found','دیدگاه پیدا نشد.',['status'=>404]);$p=(array)$request->get_json_params();$status=sanitize_key((string)($p['status']??''));if(!in_array($status,['approve','hold','spam','trash'],true))return new WP_Error('invalid_review_status','وضعیت دیدگاه معتبر نیست.',['status'=>422]);if(!wp_set_comment_status($id,$status))return new WP_Error('review_update_failed','تغییر وضعیت دیدگاه انجام نشد.',['status'=>500]);return rest_ensure_response(self::serialize_review(get_comment($id)));}
    public static function notifications(){global $wpdb;$pending=(int)wc_orders_count('pending');$failed=(int)wc_orders_count('failed');$on_hold=(int)wc_orders_count('on-hold');$reviews=(int)get_comments(['type'=>'review','status'=>'hold','count'=>true]);$low_stock=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(DISTINCT post_id) FROM {$wpdb->postmeta} WHERE meta_key='_stock' AND CAST(meta_value AS SIGNED) <= %d AND CAST(meta_value AS SIGNED) >= 0",(int)get_option('woocommerce_notify_low_stock_amount',2)));$items=[];foreach([['type'=>'pending_orders','title'=>'سفارش‌های در انتظار پرداخت','count'=>$pending,'severity'=>'warning'],['type'=>'on_hold_orders','title'=>'سفارش‌های در انتظار بررسی','count'=>$on_hold,'severity'=>'warning'],['type'=>'failed_orders','title'=>'سفارش‌های ناموفق','count'=>$failed,'severity'=>'error'],['type'=>'pending_reviews','title'=>'دیدگاه‌های در انتظار تأیید','count'=>$reviews,'severity'=>'info'],['type'=>'low_stock','title'=>'محصولات کم‌موجودی','count'=>$low_stock,'severity'=>'warning']] as $item)if($item['count']>0)$items[]=$item;return rest_ensure_response(['items'=>$items,'total'=>array_sum(array_column($items,'count')),'generated_at'=>current_time(DATE_ATOM)]);}
    public static function system(){return rest_ensure_response(['store'=>['name'=>get_bloginfo('name'),'url'=>home_url('/'),'currency'=>get_woocommerce_currency(),'timezone'=>wp_timezone_string(),'woocommerce'=>defined('WC_VERSION')?WC_VERSION:null,'wordpress'=>get_bloginfo('version'),'php'=>PHP_VERSION],'services'=>['tapin'=>['configured'=>WM_Tapin::health()],'sms'=>['provider'=>WM_Settings::get('sms_provider','melipayamak'),'configured'=>WM_Settings::get('sms_provider','melipayamak')==='farazsms'?(new WM_FarazSMS())->is_configured():(new WM_Melipayamak())->is_configured()],'auto_register'=>WM_Settings::get('tapin_auto_register','no')==='yes']]);}
    public static function devices(){return rest_ensure_response(WM_Devices::all());}
    public static function revoke_device(WP_REST_Request $request){$p=(array)$request->get_json_params();if(($p['confirm']??false)!==true)return new WP_Error('confirmation_required','تأیید لغو دسترسی الزامی است.',['status'=>409]);$id=absint($request['device_id']);if(!WM_Devices::revoke($id))return new WP_Error('device_revoke_failed','لغو دسترسی دستگاه انجام نشد.',['status'=>500]);WM_Logs::add('device_revoked','دسترسی دستگاه لغو شد.',['device_id'=>$id]);return rest_ensure_response(['revoked'=>true]);}
    public static function test_tapin(){delete_transient('woo_manager_tapin_locations');$result=WM_Tapin::locations();if(is_wp_error($result)){WM_Logs::add('tapin_test_failed',$result->get_error_message());return $result;}WM_Logs::add('tapin_test_success','اتصال واقعی تاپین با موفقیت آزمایش شد.');return rest_ensure_response(['ok'=>true,'message'=>'اتصال تاپین برقرار است.']);}
    public static function test_sms(WP_REST_Request $request){$p=(array)$request->get_json_params();$mobile=preg_replace('/\D+/','',(string)($p['mobile']??''));if(strlen($mobile)<10)return new WP_Error('invalid_mobile','شماره موبایل معتبر الزامی است.',['status'=>422]);$provider=WM_Settings::get('sms_provider','melipayamak')==='farazsms'?new WM_FarazSMS():new WM_Melipayamak();$result=$provider->send($mobile,'پیام آزمایشی اتصال Woo Manager');if(is_wp_error($result)){WM_Logs::add('sms_test_failed',$result->get_error_message());return $result;}$code=wp_remote_retrieve_response_code($result);if($code<200||$code>=300){$message='سرویس پیامک پاسخ ناموفق داد: '.$code;WM_Logs::add('sms_test_failed',$message);return new WP_Error('sms_test_failed',$message,['status'=>502]);}WM_Logs::add('sms_test_success','پیامک آزمایشی واقعی ارسال شد.',['mobile'=>substr($mobile,0,4).'***'.substr($mobile,-3)]);return rest_ensure_response(['ok'=>true,'message'=>'پیامک آزمایشی ارسال شد.']);}
    public static function logs(WP_REST_Request $request){return rest_ensure_response(WM_Logs::recent((int)($request->get_param('limit')?:100)));}
    private static function serialize_media(WP_Post $post): array {return ['id'=>$post->ID,'title'=>get_the_title($post),'filename'=>basename(get_attached_file($post->ID)),'mime_type'=>$post->post_mime_type,'url'=>wp_get_attachment_url($post->ID),'thumbnail'=>wp_get_attachment_image_url($post->ID,'medium'),'date'=>get_post_time(DATE_ATOM,true,$post)];}
    public static function media(WP_REST_Request $request){$limit=min(50,max(1,(int)($request->get_param('limit')?:30)));$page=max(1,(int)($request->get_param('page')?:1));$query=new WP_Query(['post_type'=>'attachment','post_status'=>'inherit','post_mime_type'=>'image','posts_per_page'=>$limit,'paged'=>$page,'orderby'=>'date','order'=>'DESC']);return rest_ensure_response(['items'=>array_map([self::class,'serialize_media'],$query->posts),'total'=>(int)$query->found_posts,'pages'=>(int)$query->max_num_pages,'page'=>$page]);}
    public static function upload_media(WP_REST_Request $request){$p=(array)$request->get_json_params();$filename=sanitize_file_name((string)($p['filename']??''));$mime=sanitize_mime_type((string)($p['mime_type']??''));$encoded=(string)($p['content_base64']??'');if($filename===''||strpos($mime,'image/')!==0||$encoded==='')return new WP_Error('invalid_media','نام، نوع تصویر و محتوای فایل الزامی است.',['status'=>422]);$bytes=base64_decode($encoded,true);if($bytes===false||strlen($bytes)>10*MB_IN_BYTES)return new WP_Error('invalid_media_size','تصویر نامعتبر یا بزرگ‌تر از ۱۰ مگابایت است.',['status'=>422]);$allowed=get_allowed_mime_types();if(!in_array($mime,$allowed,true))return new WP_Error('media_type_not_allowed','نوع فایل مجاز نیست.',['status'=>422]);$upload=wp_upload_bits($filename,null,$bytes);if(!empty($upload['error']))return new WP_Error('media_upload_failed',$upload['error'],['status'=>500]);$attachment_id=wp_insert_attachment(['post_mime_type'=>$mime,'post_title'=>sanitize_text_field(pathinfo($filename,PATHINFO_FILENAME)),'post_status'=>'inherit'],$upload['file']);if(is_wp_error($attachment_id))return $attachment_id;require_once ABSPATH.'wp-admin/includes/image.php';wp_update_attachment_metadata($attachment_id,wp_generate_attachment_metadata($attachment_id,$upload['file']));WM_Logs::add('media_uploaded','تصویر جدید از اپ بارگذاری شد.',['attachment_id'=>$attachment_id]);return new WP_REST_Response(self::serialize_media(get_post($attachment_id)),201);}
    private static function serialize_content(WP_Post $post): array {return ['id'=>$post->ID,'type'=>$post->post_type,'title'=>get_the_title($post),'status'=>$post->post_status,'excerpt'=>wp_strip_all_tags($post->post_excerpt),'content'=>apply_filters('the_content',$post->post_content),'date'=>get_post_time(DATE_ATOM,true,$post),'modified'=>get_post_modified_time(DATE_ATOM,true,$post),'url'=>get_permalink($post)];}
    public static function content(WP_REST_Request $request){$type=$request->get_param('type')==='page'?'page':'post';$query=new WP_Query(['post_type'=>$type,'post_status'=>['publish','draft','pending','private'],'posts_per_page'=>50,'orderby'=>'modified','order'=>'DESC']);return rest_ensure_response(array_map([self::class,'serialize_content'],$query->posts));}
    public static function update_content(WP_REST_Request $request){$id=absint($request['content_id']);$post=get_post($id);if(!$post||!in_array($post->post_type,['post','page'],true))return new WP_Error('content_not_found','محتوا پیدا نشد.',['status'=>404]);$p=(array)$request->get_json_params();$data=['ID'=>$id];if(array_key_exists('title',$p))$data['post_title']=sanitize_text_field((string)$p['title']);if(array_key_exists('content',$p))$data['post_content']=wp_kses_post((string)$p['content']);if(array_key_exists('excerpt',$p))$data['post_excerpt']=sanitize_textarea_field((string)$p['excerpt']);if(array_key_exists('status',$p)){if(!in_array($p['status'],['publish','draft','pending','private'],true))return new WP_Error('invalid_content_status','وضعیت محتوا معتبر نیست.',['status'=>422]);$data['post_status']=$p['status'];}$result=wp_update_post($data,true);if(is_wp_error($result))return $result;WM_Logs::add('content_updated','محتوای سایت از اپ ویرایش شد.',['content_id'=>$id]);return rest_ensure_response(self::serialize_content(get_post($id)));}
    public static function tapin_register(WP_REST_Request $request) {
        $wc_id=absint($request['order_id']); $order=wc_get_order($wc_id);
        if (!$order) return new WP_Error('order_not_found','سفارش پیدا نشد.',['status'=>404]);
        $mapped=WM_Order_Mapper::from_order($order,(array)$request->get_json_params());
        if (isset($mapped['error'])) return $mapped['error'];
        $result=WM_Tapin::register($mapped['payload']);
        if (!is_wp_error($result)) {
            $entries=$result['entries']??[];
            if (!empty($entries['order_id'])) { $detail=WM_Tapin::detail((int)$entries['order_id']); if(!is_wp_error($detail) && !empty($detail['entries'])) $entries=array_merge($entries,$detail['entries']); }
            $result['entries']=$entries;
            $order->update_meta_data('_woo_manager_tapin',$entries); $order->update_meta_data('_tapin_order_id',$entries['order_id']??''); $order->update_meta_data('_tapin_uuid',$entries['id']??''); $order->update_meta_data('_tracking_number',$entries['barcode']??''); $order->save();
            if (!empty($entries['barcode'])) self::send_tracking_sms($order,(string)$entries['barcode']);
        }
        return $result;
    }
    private static function send_tracking_sms(WC_Order $order,string $code): void {
        $message=str_replace(['{tracking_code}','{order_id}'],[$code,(string)$order->get_id()],WM_Settings::get('tracking_message','سفارش شما ارسال شد. کد رهگیری: {tracking_code}'));
        $provider=WM_Settings::get('sms_provider','melipayamak')==='farazsms'?new WM_FarazSMS():new WM_Melipayamak();
        $sent=$provider->send($order->get_billing_phone(),$message); $order->add_order_note(is_wp_error($sent)?'خطا در ارسال پیامک رهگیری: '.$sent->get_error_message():'پیامک کد رهگیری ارسال شد.');
    }
    public static function auto_register(int $order_id): void {
        if(WM_Settings::get('tapin_auto_register','no')!=='yes')return; $order=wc_get_order($order_id); if(!$order||$order->get_meta('_tapin_order_id'))return;
        $mapped=WM_Order_Mapper::from_order($order,[]); if(isset($mapped['error'])){$order->add_order_note('ثبت خودکار تاپین انجام نشد: '.$mapped['error']->get_error_message());return;}
        $result=WM_Tapin::register($mapped['payload']); if(is_wp_error($result)){$order->add_order_note('خطای تاپین: '.$result->get_error_message());return;}
        $entries=$result['entries']??[]; if(!empty($entries['order_id'])){$detail=WM_Tapin::detail((int)$entries['order_id']);if(!is_wp_error($detail)&&!empty($detail['entries']))$entries=array_merge($entries,$detail['entries']);}
        $order->update_meta_data('_tapin_order_id',$entries['order_id']??'');$order->update_meta_data('_tapin_uuid',$entries['id']??'');$order->update_meta_data('_tracking_number',$entries['barcode']??'');$order->save();if(!empty($entries['barcode']))self::send_tracking_sms($order,(string)$entries['barcode']);
    }
    public static function tapin_label(WP_REST_Request $r) { $params=(array)$r->get_json_params(); $ids=(array)($params['ids']??[]); if(!$ids)return new WP_Error('missing_ids','شناسه مرسوله‌ها الزامی است.',['status'=>422]); $html=WM_Tapin::label($ids); return is_wp_error($html)?$html:new WP_REST_Response($html,200,['Content-Type'=>'text/html; charset=utf-8']); }
    public static function tapin_invoice(WP_REST_Request $r) { $params=(array)$r->get_json_params(); $ids=(array)($params['ids']??[]); if(!$ids)return new WP_Error('missing_ids','شناسه سفارش‌های تاپین الزامی است.',['status'=>422]); $html=WM_Tapin::invoice($ids); return is_wp_error($html)?$html:new WP_REST_Response($html,200,['Content-Type'=>'text/html; charset=utf-8']); }
    public static function tapin_pdf(WP_REST_Request $r) { $p=(array)$r->get_json_params();$ids=(array)($p['ids']??[]);$type=($p['type']??'invoice')==='label'?'label':'invoice';if(!$ids)return new WP_Error('missing_ids','شناسه مرسوله‌ها الزامی است.',['status'=>422]);$html=$type==='label'?WM_Tapin::label($ids):WM_Tapin::invoice($ids);if(is_wp_error($html))return $html;return WM_PDF::from_html($html,'tapin-'.$type.'-'.gmdate('Ymd-His').'.pdf');}
}
